### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by cu-noyvirt** [RemotePixel/remotepixel-tiler#11]
Sorry for creating trouble. Probably it is something on my side but I am stuck when trying to build the lambda package.  I keep getting error when trying to build the package following the Readme instructions. It seems that the error comes when the docker is building rasterio dependencies in the last line of docker file. Could you please try to replicate it. 

Here are the details:  At the point when
 make package && make test 

I get:Step 7/7 : RUN pip3 install . --no-binary numpy,rasterio -t $PACKAGE_TMP -U
 ---> Running in a3ce0f9dbdc8
Processing /var/task
Collecting aws-sat-api~=2.0 (from remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/05/6c/a8f0e07fcbaa346adcbfd5e68489b4b3734d422379fc3dbb70fe03e79c10/aws_sat_api-2.0.2.tar.gz
Collecting lambda-proxy~=4.1 (from remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/27/e0/beae2f668296c7730776ab83da7a6afd249e570f3636ec4af85cf13fb82f/lambda-proxy-4.1.4.tar.gz
Collecting rio-color (from remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/c3/b1/a506de52f1bfe4816d686588c3e0835f81d4af063228660a588dd495a817/rio_color-1.0.0-cp36-cp36m-manylinux1_x86_64.whl (120kB)
Collecting rio-tiler>=1.2.6 (from remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/98/1d/79f983b47716f8950aed00a36dbbc27845f275916b0c07073d4e2fa3e4b6/rio-tiler-1.2.10.tar.gz (109kB)
Collecting rio-tiler-mvt (from remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/9b/f2/6b48d33a35d13ace700d055f297aa75f58af18ce1271554214dfc43b5d6a/rio-tiler-mvt-0.0.1.dev1.tar.gz (54kB)
Collecting numpy==1.16 (from remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/04/b6/d7faa70a3e3eac39f943cc6a6a64ce378259677de516bd899dd9eb8f9b32/numpy-1.16.0.zip (5.1MB)
Collecting vtzero (from remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/4a/70/d5171240be0bfe4d6ae0002a19c9ee0bd17d1a7670facfad471a023c58ad/vtzero-0.0.1b1.tar.gz (80kB)
Collecting boto3 (from aws-sat-api~=2.0->remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/3d/2b/c641f5e91970c22ce92cbfb22cb468b24c08de035102d93c09eeae4f2136/boto3-1.9.213-py2.py3-none-any.whl (128kB)
Collecting rio-mucho (from rio-color->remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/8a/ba/e9a23efc6a8ffe6b2340c9f1040cd26a730754c75a58061c9302c66156fa/rio_mucho-1.0.0-py3-none-any.whl
Collecting click (from rio-color->remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting rasterio>=1.0a11 (from rio-color->remotepixel-tiler==4.1.0)
  Downloading https://files.pythonhosted.org/packages/0c/62/91d23e91e7c2b6db1ba208c1e1ced59554a0e651087bf0a854d915f08d10/rasterio-1.0.25.tar.gz (2.1MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /var/lang//bin/python3.6 /var/lang/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wlsmiobt/overlay --no-warn-script-location --no-binary numpy,rasterio --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython numpy
       cwd: None

**Comment by vincentsarago** [comment]
@cu-noyvirt I just pushed some change to the master branch and it should be fine now (I guess it was the numpy build error reported in https://github.com/RemotePixel/amazonlinux-gdal/issues/25

**Comment by cu-noyvirt** [comment]
It works fine now. Cheers
