### ISSUE TITLE
serverless error when trying to deploy cbers service

### ISSUE THREAD

**Issue by mvmendes** [RemotePixel/remotepixel-tiler#13]
When I tried to execute sls deploy command (unchanged version of this repository and commands executed was the same exposed on readme), I got this:
  Serverless Error ---------------------------------------

  An error occurred: TilerLambdaFunction - Layer version arn:aws:lambda:us-east-1:524387336408:layer:gdal24-py37-geo:2 does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 5c17823a-3bc5-4539-ab65-bc85b65b808f).

**Comment by vincentsarago** [comment]
@mvmendes please update your version with on arn from https://github.com/lambgeo/geo-layer
